Support Tigerbeetle 0.15.5
tigerbeetle-rust/tigerbeetle-unofficial pull request #19
Opened 2024-08-16 00:00 UTC by jeffutter

This adds support for Tigerbeetle `0.15.5`. Besides a few bits accommodating changes to `build.zig`, the significant changes are support for client-side allocation of packets (the API was removed in `0.15.4`) and locking around access to `tb_client_t` when sending packets or deconstructing. This was implemented in `0.15.4` for the official clients [such as this go implementation](https://github.com/tigerbeetle/tigerbeetle/commit/c0d336bab404dcff3b64e0ae473a7c2c78663569).

I am inexperienced with `c` `ffi` bindings at this level, so please help me double-check the memory management.

Any other feedback is welcome.

2024-08-31 11:12 UTC, dyc3 reviewed
I haven't tested it, but at a glance this looks good to me.

2024-10-14 06:56 UTC, dnlsndr commented
LGTM! I'm very interested in this update, is there any way I could help?

2024-10-29 13:36 UTC, dyc3 commented
When running the example, the sys crate fails to build:

```
error: failed to run custom build command for `tigerbeetle-unofficial-sys v0.4.1+0.15.5 (/home/carson/Documents/code/other/tigerbeetle-rs/sys)`

Caused by:
  process didn't exit successfully: `/home/carson/Documents/code/other/tigerbeetle-rs/target/debug/build/tigerbeetle-unofficial-sys-3fa4974dcddfecea/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-changed=src/wrapper.h

  --- stderr
  thread 'main' panicked at sys/build.rs:92:10:
  running download script: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It appears the `zig/download` script no longer exists.

2024-10-29 14:26 UTC, dyc3 reviewed
I've tested this with the example, and with these changes it works just fine.

2024-11-04 17:50 UTC, tyranron requested changes

2024-11-04 17:50 UTC, tyranron commented on core/src/packet.rs
> +    pub fn submit(mut self) -> Result<(), ClientClosedError> {
@jeffutter I don't really understand this change. Judging from the body, it doesn't return this error anywhere. So, why have it in the signature?

2024-11-04 18:21 UTC, zetanumbers commented on core/src/packet.rs
> +    pub(super) raw: ManuallyDrop<*mut sys::tb_packet_t>,
`ManuallyDrop` on a pointer? Why?

2024-11-04 18:24 UTC, zetanumbers commented on core/src/packet.rs
> +            self.raw.drop_in_place();
This code does nothing, see comment above.

2024-11-04 18:28 UTC, zetanumbers commented on core/src/handle.rs
> +// impl<U> Copy for ClientHandle<'_, U> where U: UserDataPtr {}
This change is unsubstantiated.

2024-11-04 18:33 UTC, zetanumbers commented on core/src/lib.rs
> +    raw: Arc<Mutex<sys::tb_client_t>>,
There should be no need to use mutex there. In case `tb_client_t` became thread-unsafe, `Client` itself should become `!Sync` instead.

2024-11-14 13:48 UTC, zetanumbers commented
Superseded by #24

2024-11-14 13:48 UTC, closed without merging