Fix builds inside Docker environment
tigerbeetle-rust/tigerbeetle-unofficial pull request #23
Opened 2024-11-04 17:28 UTC by 50U10FCA7

Resolves #20

2024-11-04 17:32 UTC, 50U10FCA7 commented
### FCM
```
Fix builds inside Docker environment (#23, #20)

- provide `TIGERBEETLE_COMMIT` in `tigerbeetle-unofficial-sys` crate build script

Additionally:
- bump project dependencies to the latest versions
```

2024-11-21 19:14 UTC, tyranron requested changes
@50U10FCA7 is this still actual? Could you update to the latest `master`?

2024-11-22 13:31 UTC, tyranron approved these changes

2024-11-22 13:33 UTC, merged

2024-11-22 16:05 UTC, zetanumbers commented on CONTIBUTING.md
There should be a step to check diff files of C client header and its usage example between versions.