Support new TigerBeetle functionality
tigerbeetle-rust/tigerbeetle-unofficial pull request #26
Opened 2024-11-05 13:47 UTC by 50U10FCA7

Requires #24

# Problem

[`query_accounts`](https://docs.tigerbeetle.com/reference/requests/query_accounts) and [`query_transfers`](https://docs.tigerbeetle.com/reference/requests/query_transfers) TigerBeetle requests (and [`QueryFilter`](https://docs.tigerbeetle.com/reference/query-filter/)) not yet supported.

# Solution

Implement:
- [`QueryFilter`](https://docs.tigerbeetle.com/reference/query-filter) record;
- [`query_accounts`](https://docs.tigerbeetle.com/reference/requests/query_accounts) request;
- [`query_transfers`](https://docs.tigerbeetle.com/reference/requests/query_transfers) request.

2024-11-05 14:13 UTC, 50U10FCA7 commented
### FCM
```markdown
Support new TigerBeetle functionality (#26)

- add `QueryFilter`
- impl `Client::query_accounts` and `Client::query_transfers`
```

2024-11-25 17:25 UTC, tyranron requested changes

2024-11-25 17:29 UTC, 50U10FCA7 commented on core/src/query_filter.rs
> +        f.debug_struct("AccountFilter")
Typo

2024-11-25 17:44 UTC, 50U10FCA7 commented on core/src/handle.rs
> +    pub fn packet(self, user_data: U, operation: impl Into<packet::Operation>) -> Packet<'a, U> {
@tyranron #34

2024-11-25 19:01 UTC, tyranron approved these changes
@50U10FCA7 LGTM, thanks! 🍻

@zetanumbers the code changes are relatively simple and mostly copy-pasted from the existing sources. Please, take a look, and if you don't have any objections, I'll merge in 2 days or so.

2024-12-02 13:56 UTC, merged